import './global.css';
import { Footer, Navbar, Providers } from '../components';

export const metadata = {
  title: 'ChordHub',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <div className="bg-base-200">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
