export * from './chevron-right.icon';
export * from './click.icon';
export * from './filter.icon';
export * from './github.icon';
export * from './info.icon';
export * from './magnifying-glass-icon';
export * from './music.icon';
export * from './play.icon';
export * from './x-cicle.icon';
